import { ParallaxLayerConfig, RefinedBiome } from './refinedBiomeSchema';

export const DEFAULT_PARALLAX_LAYERS: Record<string, ParallaxLayerConfig[]> = {
  mourne_ashen_steppes: [
    {
      layerIndex: -5,
      name: 'Volcanic Sky & Ash Storm',
      speedFactorX: 0.04,
      speedFactorY: 0.02,
      opacity: 1.0,
      tintColor: '#1e1b2e',
      gradientTop: '#0f0c1b',
      gradientBottom: '#311c28',
      proceduralTheme: 'celestial_sky',
      repeatX: true,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: -4,
      name: 'Distant Basalt Peaks & Craters',
      speedFactorX: 0.12,
      speedFactorY: 0.06,
      opacity: 0.85,
      tintColor: '#2b1e2a',
      proceduralTheme: 'distant_mountain_range',
      repeatX: true,
      repeatY: false,
      offsetY: 40,
      scale: 1.0
    },
    {
      layerIndex: -3,
      name: 'Midground Obsidian Monoliths',
      speedFactorX: 0.28,
      speedFactorY: 0.14,
      opacity: 0.8,
      tintColor: '#3a2536',
      proceduralTheme: 'ruined_megastructures',
      repeatX: true,
      repeatY: false,
      offsetY: 60,
      scale: 1.0
    },
    {
      layerIndex: -2,
      name: 'Nearer Basalt Arches & Fissures',
      speedFactorX: 0.5,
      speedFactorY: 0.28,
      opacity: 0.75,
      tintColor: '#432938',
      proceduralTheme: 'cavern_pillars',
      repeatX: true,
      repeatY: false,
      offsetY: 80,
      scale: 1.0
    },
    {
      layerIndex: -1,
      name: 'Immediate Cinder Wall Backdrop',
      speedFactorX: 0.78,
      speedFactorY: 0.55,
      opacity: 0.65,
      tintColor: '#27202b',
      proceduralTheme: 'interior_masonry_backwall',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 0,
      name: 'Main Gameplay Plane (Solid Tiles & Entities)',
      speedFactorX: 1.0,
      speedFactorY: 1.0,
      opacity: 1.0,
      tintColor: '#ffffff',
      proceduralTheme: 'custom_image',
      repeatX: false,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 1,
      name: 'Foreground Smoldering Ash & Cinders',
      speedFactorX: 1.35,
      speedFactorY: 1.25,
      opacity: 0.7,
      tintColor: '#f97316',
      proceduralTheme: 'foreground_overgrowth',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    }
  ],

  luminescent_hollow: [
    {
      layerIndex: -5,
      name: 'Abyssal Cavern Ceiling & Spore Mist',
      speedFactorX: 0.03,
      speedFactorY: 0.02,
      opacity: 1.0,
      tintColor: '#030712',
      gradientTop: '#020617',
      gradientBottom: '#042f2e',
      proceduralTheme: 'celestial_sky',
      repeatX: true,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: -4,
      name: 'Deep Mycelium Cavern Silhouette',
      speedFactorX: 0.1,
      speedFactorY: 0.05,
      opacity: 0.9,
      tintColor: '#083344',
      proceduralTheme: 'distant_mountain_range',
      repeatX: true,
      repeatY: false,
      offsetY: 30,
      scale: 1.0
    },
    {
      layerIndex: -3,
      name: 'Colossal Giant Mushroom Canopies',
      speedFactorX: 0.25,
      speedFactorY: 0.12,
      opacity: 0.85,
      tintColor: '#0e7490',
      proceduralTheme: 'ruined_megastructures',
      repeatX: true,
      repeatY: false,
      offsetY: 50,
      scale: 1.0
    },
    {
      layerIndex: -2,
      name: 'Bioluminescent Crystal Pillars',
      speedFactorX: 0.48,
      speedFactorY: 0.25,
      opacity: 0.8,
      tintColor: '#164e63',
      proceduralTheme: 'cavern_pillars',
      repeatX: true,
      repeatY: false,
      offsetY: 70,
      scale: 1.0
    },
    {
      layerIndex: -1,
      name: 'Luminescent Spore Wall Backdrop',
      speedFactorX: 0.75,
      speedFactorY: 0.5,
      opacity: 0.6,
      tintColor: '#042f2e',
      proceduralTheme: 'interior_masonry_backwall',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 0,
      name: 'Main Gameplay Plane (Solid Turf & Platforms)',
      speedFactorX: 1.0,
      speedFactorY: 1.0,
      opacity: 1.0,
      tintColor: '#ffffff',
      proceduralTheme: 'custom_image',
      repeatX: false,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 1,
      name: 'Foreground Hanging Bioluminescent Tendrils',
      speedFactorX: 1.3,
      speedFactorY: 1.2,
      opacity: 0.75,
      tintColor: '#22d3ee',
      proceduralTheme: 'foreground_overgrowth',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    }
  ],

  cryo_frost_shelf: [
    {
      layerIndex: -5,
      name: 'Aurora Borealis Polar Sky',
      speedFactorX: 0.05,
      speedFactorY: 0.02,
      opacity: 1.0,
      tintColor: '#020617',
      gradientTop: '#030712',
      gradientBottom: '#0c4a6e',
      proceduralTheme: 'celestial_sky',
      repeatX: true,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: -4,
      name: 'Glacial Mountain Needles & Ridge',
      speedFactorX: 0.14,
      speedFactorY: 0.07,
      opacity: 0.9,
      tintColor: '#075985',
      proceduralTheme: 'distant_mountain_range',
      repeatX: true,
      repeatY: false,
      offsetY: 45,
      scale: 1.0
    },
    {
      layerIndex: -3,
      name: 'Permafrost Glacial Arcs & Colonnades',
      speedFactorX: 0.3,
      speedFactorY: 0.15,
      opacity: 0.85,
      tintColor: '#0284c7',
      proceduralTheme: 'ruined_megastructures',
      repeatX: true,
      repeatY: false,
      offsetY: 65,
      scale: 1.0
    },
    {
      layerIndex: -2,
      name: 'Ice Stalactites & Frost Needle Formations',
      speedFactorX: 0.52,
      speedFactorY: 0.3,
      opacity: 0.8,
      tintColor: '#38bdf8',
      proceduralTheme: 'cavern_pillars',
      repeatX: true,
      repeatY: false,
      offsetY: 80,
      scale: 1.0
    },
    {
      layerIndex: -1,
      name: 'Chiseled Permafrost Wall Backdrop',
      speedFactorX: 0.8,
      speedFactorY: 0.58,
      opacity: 0.65,
      tintColor: '#0c4a6e',
      proceduralTheme: 'interior_masonry_backwall',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 0,
      name: 'Main Gameplay Plane (Glacial Platforms & Ice)',
      speedFactorX: 1.0,
      speedFactorY: 1.0,
      opacity: 1.0,
      tintColor: '#ffffff',
      proceduralTheme: 'custom_image',
      repeatX: false,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 1,
      name: 'Foreground Blown Snow Particles & Icicles',
      speedFactorX: 1.4,
      speedFactorY: 1.3,
      opacity: 0.8,
      tintColor: '#e0f2fe',
      proceduralTheme: 'foreground_overgrowth',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    }
  ]
};

export const createDefaultParallaxLayers = (biomeName: string, baseColor: string): ParallaxLayerConfig[] => {
  return [
    {
      layerIndex: -5,
      name: `${biomeName} Deep Sky / Astral Horizon`,
      speedFactorX: 0.04,
      speedFactorY: 0.02,
      opacity: 1.0,
      tintColor: '#0b0f19',
      gradientTop: '#020617',
      gradientBottom: baseColor,
      proceduralTheme: 'celestial_sky',
      repeatX: true,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: -4,
      name: `${biomeName} Far Skyline & Ridge Silhouettes`,
      speedFactorX: 0.12,
      speedFactorY: 0.06,
      opacity: 0.85,
      tintColor: baseColor,
      proceduralTheme: 'distant_mountain_range',
      repeatX: true,
      repeatY: false,
      offsetY: 40,
      scale: 1.0
    },
    {
      layerIndex: -3,
      name: `${biomeName} Ancient Ruins & Megastructures`,
      speedFactorX: 0.28,
      speedFactorY: 0.14,
      opacity: 0.8,
      tintColor: baseColor,
      proceduralTheme: 'ruined_megastructures',
      repeatX: true,
      repeatY: false,
      offsetY: 60,
      scale: 1.0
    },
    {
      layerIndex: -2,
      name: `${biomeName} Nearer Cavern Spikes & Arches`,
      speedFactorX: 0.5,
      speedFactorY: 0.28,
      opacity: 0.75,
      tintColor: baseColor,
      proceduralTheme: 'cavern_pillars',
      repeatX: true,
      repeatY: false,
      offsetY: 80,
      scale: 1.0
    },
    {
      layerIndex: -1,
      name: `${biomeName} Immediate Backwall Backdrop`,
      speedFactorX: 0.78,
      speedFactorY: 0.55,
      opacity: 0.65,
      tintColor: '#1e293b',
      proceduralTheme: 'interior_masonry_backwall',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 0,
      name: 'Main Gameplay Plane (Solid Tiles)',
      speedFactorX: 1.0,
      speedFactorY: 1.0,
      opacity: 1.0,
      tintColor: '#ffffff',
      proceduralTheme: 'custom_image',
      repeatX: false,
      repeatY: false,
      offsetY: 0,
      scale: 1.0
    },
    {
      layerIndex: 1,
      name: `${biomeName} Foreground Overgrowth & Shrouds`,
      speedFactorX: 1.35,
      speedFactorY: 1.25,
      opacity: 0.7,
      tintColor: baseColor,
      proceduralTheme: 'foreground_overgrowth',
      repeatX: true,
      repeatY: true,
      offsetY: 0,
      scale: 1.0
    }
  ];
};
